# Usage
#   Development:        docker compose --env-file env/env.dev up -d
#   Production:         docker compose --env-file env/.env.prod up -d
#   Download:           docker compose pull
#   Stop:               docker compose down
#   Destroy:            docker compose down -v --remove-orphans
#   DB URL:             postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:${POSTGRES_PORT}/${POSTGRES_DB}

name: bydeusz-business-boilerplate

# Include all services by default
include:
  - services/docker-storage.yml
  - services/docker-cms.yml
  - services/docker-db.yml

networks:
  app_network:
    driver: bridge